{{- if and ( not (lookup "apps/v1" "Deployment" .Release.Namespace "hwameistor-local-disk-csi-controller") ) .Values.localDiskManager.enableCSI }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hwameistor-local-disk-csi-controller
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwameistor-local-disk-csi-controller
  template:
    metadata:
      labels:
        app: hwameistor-local-disk-csi-controller
    spec:
      priorityClassName: system-cluster-critical
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hwameistor-local-disk-manager
            topologyKey: topology.disk.hwameistor.io/node
      serviceAccount: hwameistor-admin
      containers:
        - name: provisioner
          image: {{ .Values.k8sImageRegistry}}/{{ .Values.localDiskManagerCSIController.provisioner.imageRepository}}:{{ .Values.localDiskManagerCSIController.provisioner.tag}}
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ADDRESS)"
            - "--leader-election=true"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
            - "--extra-create-metadata=true"
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: attacher
          image: {{ .Values.k8sImageRegistry}}/{{ .Values.localDiskManagerCSIController.attacher.imageRepository}}:{{ .Values.localDiskManagerCSIController.attacher.tag}}
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ADDRESS)"
            - "--leader-election=true"
            - "--timeout=120s"
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ template "hwameistor.kubeletRootDir" . }}/plugins/disk.hwameistor.io
            type: DirectoryOrCreate
{{- end -}}
