apiVersion: v1
kind: ConfigMap
metadata:
  name: hwameistor-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  hwameistor-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: hwameistor-scheduler
        plugins:
          filter:
            enabled:
              - name: hwameistor-scheduler-plugin
          reserve:
            enabled:
              - name: hwameistor-scheduler-plugin
          score:
            enabled:
              - name: hwameistor-scheduler-plugin
                weight: 10
    leaderElection:
      leaderElect: true
      resourceName: hwameistor-scheduler
      