kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hwameistor
  namespace: local-storage-system
spec:
  selector:
    matchLabels:
      app: hwameistor
  template:
    metadata:
      labels:
        app: hwameistor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: csi.driver.hwameistor.io/local-storage
                operator: In
                values:
                - "true"
      serviceAccount: storage-admin
      priorityClassName: system-node-critical
      hostNetwork: false
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/lvm.hwameistor.io/csi.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/lvm.hwameistor.io /registration/lvm.hwameistor.io-reg.sock"]
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: member
          image: ghcr.io/hwameistor/local-storage:v0.0.2
          imagePullPolicy: IfNotPresent
          args:
            - --nodename=$(MY_NODENAME)
            - --namespace=$(POD_NAMESPACE)
            - --csi-address=$(CSI_ENDPOINT)
            - --http-port=80
            - --debug=true
          ports:
          - containerPort: 80
            name: healthz
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/lvm.hwameistor.io/csi.sock
            - name: NODE_ANNOTATION_KEY_STORAGE_IPV4
              value: localstorage.hwameistor.io/storage-ipv4
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: "Bidirectional"
            - name: registration-dir
              mountPath: /var/lib/kubelet/plugins_registry
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: host-dev
              mountPath: /dev
            - name: host-etc-drbd
              mountPath: /etc/drbd.d
              mountPropagation: "Bidirectional"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lvm.hwameistor.io
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-etc-drbd
          hostPath:
            path: /etc/drbd.d
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
