apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-hdd-disk
provisioner: lvm.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  replicaNumber: "1"
  poolClass: "HDD"
  poolType: "REGULAR"
  volumeKind: "DISK"
  csi.storage.k8s.io/fstype: "xfs"
