- "{{ .global.hwameistorImageRegistry}}/{{ .scheduler.imageRepository}}:{{ .scheduler.tag}}"
- "{{ .global.hwameistorImageRegistry }}/{{ .admission.imageRepository }}:{{ .admission.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .evictor.imageRepository }}:{{ .evictor.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManager.registrar.imageRepository }}:{{ .localDiskManager.registrar.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .localDiskManager.manager.imageRepository }}:{{ .localDiskManager.manager.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManagerCSIController.provisioner.imageRepository }}:{{ .localDiskManagerCSIController.provisioner.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localDiskManagerCSIController.attacher.imageRepository }}:{{ .localDiskManagerCSIController.attacher.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorage.registrar.imageRepository }}:{{ .localStorage.registrar.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .localStorage.member.imageRepository }}:{{ .localStorage.member.tag }}"
- "{{ .localStorage.migrate.rclone.imageRepository }}:{{ .localStorage.migrate.rclone.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorageCSIController.provisioner.imageRepository }}:{{ .localStorageCSIController.provisioner.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorageCSIController.attacher.imageRepository }}:{{ .localStorageCSIController.attacher.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorageCSIController.resizer.imageRepository }}:{{ .localStorageCSIController.resizer.tag }}"
- "{{ .global.k8sImageRegistry }}/{{ .localStorageCSIController.healthMonitor.imageRepository }}:{{ .localStorageCSIController.healthMonitor.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .apiserver.imageRepository }}:{{ .apiserver.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .exporter.imageRepository }}:{{ .exporter.tag }}"
- "{{ .global.hwameistorImageRegistry }}/{{ .ui.imageRepository }}:{{ .ui.tag }}"
