scheduler:
  replicas: 3
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

admission:
  replicas: 3
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

evictor:
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

exporter:
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

apiserver:
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

ui:
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 1m
      memory: 20Mi

localDiskManager:
  tolerationsOnMaster: false
  registrar:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  manager:
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 1m
        memory: 20Mi

localDiskManagerCSIController:
  replicas: 3
  priorityClassName: system-node-critical
  provisioner:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  attacher:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi

localStorage:
  tolerationsOnMaster: false
  priorityClassName: system-node-critical
  registrar:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  member:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi

localStorageCSIController:
  replicas: 3
  priorityClassName: system-node-critical
  provisioner:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  attacher:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  resizer:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi
  healthMonitor:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 1m
        memory: 20Mi