name: cherry_pick

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  cherry_pick_release_v1_0:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the GITHUB_TOKEN to write to the repository
      pull-requests: write
    name: Cherry pick into release-v1.0
    if: ${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick-v1') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v1.0
        uses: xealth/cherry-pick-action@v1.0.0
        with:
          branch: release/v1.0.0
          labels: |
            cherry-pick
#          reviewers: |
#            aReviewerUser

